version: '3.3'

services:

    shopping-mate:
        build: .
        container_name: shopping-mate-front
        volumes:
        - '.:/app'
        - '/app/node_modules'
        ports:
        - '3000:3000'
        stdin_open: true
